#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2017-05-15 19:18
# Email        : kaleo1990@hotmail.com
# Filename     : dbrestore
# Description  : 
# ******************************************************
mysql -uroot -pkaleozhou guanwang < guanwang.sql
